

export const IDResolver = {
    play_button : 'play-button',
    to_commands_button:'navigate-commands',
    command_list : 'command-list',
    add_command_button: 'add-command-button',
    delete_command_button  : 'delete-command-button',
    start_game:'start-game',
    game_timer:'game-timer',
    start_timer:'start-timer',
    stop_timer:'stop-timer',
    skip_word:'skip-word',
    page_container:'page-container',
    modal_window: 'modal-window',
    modal_window_body : 'modal-window-body',
    modal_window_close_button : 'modal-window-close-button',
    login_form : 'login-form',
    word_mange : 'word-manage',
    admin_language_dropdown : 'choose-lang',
    admin_level_dropdown : 'choose-level',
    admin_add_new_input : 'word-mange-add-input',
    admin_add_new_button : 'word-mange-add-button',
    game_word_to_guess : 'word-to-guess',
    game_guessed_score : 'guessed-score',
    game_skipped_score : 'skipped-score',
    game_guessed_button:'guessed-word',
    command_result_skipped_words : 'skipped-words',
    command_result_guessed_words : 'guessed-words',
    command_name:'command-name',
    command_result:'command-result',
    team_name : 'team-name'
}
